/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppGame {
    }
}
declare global {
    interface HTMLAppGameElement extends Components.AppGame, HTMLStencilElement {
    }
    var HTMLAppGameElement: {
        prototype: HTMLAppGameElement;
        new (): HTMLAppGameElement;
    };
    interface HTMLElementTagNameMap {
        "app-game": HTMLAppGameElement;
    }
}
declare namespace LocalJSX {
    interface AppGame {
    }
    interface IntrinsicElements {
        "app-game": AppGame;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-game": LocalJSX.AppGame & JSXBase.HTMLAttributes<HTMLAppGameElement>;
        }
    }
}
