/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppBoard {
    }
    interface AppGame {
    }
    interface AppInfo {
    }
    interface AppSquare {
        "index": number;
        "label": string;
    }
}
declare global {
    interface HTMLAppBoardElement extends Components.AppBoard, HTMLStencilElement {
    }
    var HTMLAppBoardElement: {
        prototype: HTMLAppBoardElement;
        new (): HTMLAppBoardElement;
    };
    interface HTMLAppGameElement extends Components.AppGame, HTMLStencilElement {
    }
    var HTMLAppGameElement: {
        prototype: HTMLAppGameElement;
        new (): HTMLAppGameElement;
    };
    interface HTMLAppInfoElement extends Components.AppInfo, HTMLStencilElement {
    }
    var HTMLAppInfoElement: {
        prototype: HTMLAppInfoElement;
        new (): HTMLAppInfoElement;
    };
    interface HTMLAppSquareElement extends Components.AppSquare, HTMLStencilElement {
    }
    var HTMLAppSquareElement: {
        prototype: HTMLAppSquareElement;
        new (): HTMLAppSquareElement;
    };
    interface HTMLElementTagNameMap {
        "app-board": HTMLAppBoardElement;
        "app-game": HTMLAppGameElement;
        "app-info": HTMLAppInfoElement;
        "app-square": HTMLAppSquareElement;
    }
}
declare namespace LocalJSX {
    interface AppBoard {
    }
    interface AppGame {
    }
    interface AppInfo {
    }
    interface AppSquare {
        "index"?: number;
        "label"?: string;
    }
    interface IntrinsicElements {
        "app-board": AppBoard;
        "app-game": AppGame;
        "app-info": AppInfo;
        "app-square": AppSquare;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-board": LocalJSX.AppBoard & JSXBase.HTMLAttributes<HTMLAppBoardElement>;
            "app-game": LocalJSX.AppGame & JSXBase.HTMLAttributes<HTMLAppGameElement>;
            "app-info": LocalJSX.AppInfo & JSXBase.HTMLAttributes<HTMLAppInfoElement>;
            "app-square": LocalJSX.AppSquare & JSXBase.HTMLAttributes<HTMLAppSquareElement>;
        }
    }
}
